joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1
  pid: {p: 1200.0, i: 620.0, d: 1000.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2
  pid: {p: 50000.0, i: 100, d: 2000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_1
  pid: {p: 80000.0, i: 540, d: 680.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: gripper_2
  pid: {p: 80000.0, i: 540, d: 680.0}
